%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Gillian\Documents\SEED\DataMotorFinal.csv
%
% Auto-generated by MATLAB on 09-Oct-2020 14:40:55

%% Setup the Import Options and import the data
clear
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["micro_s", "Pos", "AngVel", "seconds1"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("D:\Gillian\Documents\SEED\DataMotorFinal.csv", opts);

%% Convert to output type
micro_s = tbl.micro_s;
Pos = tbl.Pos;
AngVel = tbl.AngVel;
seconds1 = tbl.seconds1;

%% Clear temporary variables
clear opts tbl

%% Plot Simulations and Real Data for PID Controller
K = 13.89/7.4;
sigma = 19.25;
close all
out=sim('PIControllerMotorProj');

figure(1)
hold on
title("PID Controller: Position")
xlabel("Seconds")
ylabel("Radians")
plot(seconds1,Pos)
plot(out.Position)
legend("Real","Simulated")
hold off
figure(2)
hold on
title("PID Controller: Velocity")
xlabel("Seconds")
ylabel("Radians/Second")
plot(seconds1,AngVel)
plot(out.Velocity)
legend("Real","Simulated")
hold off
