%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Gillian\Documents\SEED\DataMotorFull.csv
%
% Auto-generated by MATLAB on 05-Oct-2020 22:03:57

%% Setup the Import Options and import the data
clear
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["micro", "AngPos", "AngVel", "Sec"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("D:\Gillian\Documents\SEED\DataMotorFull.csv", opts);

%% Convert to output type
micro = tbl.micro;
AngPos = tbl.AngPos;
AngVel = tbl.AngVel;
Sec = tbl.Sec;

%% Clear temporary variables
clear opts tbl

%% Step Response Experiement
close all
out=sim('MotorTransfer');

figure(1)
hold on
title("Step Response Exp: Position")
xlabel("Seconds")
ylabel("Radians")
plot(Sec,AngPos)
plot(out.Position)
legend("Real","Simulated")
hold off
figure(2)
hold on
title("Step Response Exp: Velocity")
xlabel("Seconds")
ylabel("Radians/Second")
plot(Sec,AngVel)
plot(out.Velocity)
legend("Real","Simulated")
hold off
